name: Install deps and cache
description: Install dependencies and caching
inputs:
  bun-version:
    description: "Bun version to install"
    required: false
    default: "latest"
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
    - uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
    - name: Install deps
      shell: bash
      run: bun install
