networks:
  caddy:
    external: true
services:
  web:
    image: earthchnt/react-gh:latest
    container_name: react-gh
    ports:
      - "3000:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - caddy
