name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install and Cache deps
        uses: ./.github/actions/install-cache
        with:
          bun-version: ${{ vars.BUN_VERSION }}

      - name: Build
        run: bun run build

      - name: Lint dist
        run: ls dist

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

  deploy:
    name: Deploy to surge
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: ./dist
      - name: Deploy to surge
        id: deploy
        uses: ./.github/actions/deploy-surge
        with:
          domain: react-gh.surge.sh
          token: ${{ secrets.SURGE_TOKEN }}
          email: ${{ vars.SURGE_EMAIL }}
          dist-folder: ./dist
