name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install and Cache deps
        uses: ./.github/actions/install-cache
        with:
          bun-version: ${{ vars.BUN_VERSION }}

      - name: Build
        run: bun run build

      - name: Lint dist
        uses: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        run: echo "Deploying..."
