name: Lint Code
on:
  push:
    branches:
      - main
      - features/**
      - "!features/authen"
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  lint:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Print bun version
        run: echo "Bun version:${{ vars.BUN_VERSION }}"

      - name: Clone repo
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint
